import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // dockerSidebar: [{ type: 'autogenerated', dirName: 'docker' }],
  golangSidebar: [
    {
      type: 'category',
      label: 'Golang',
      items: ['golang/intro'],
    },
  ],
  dsaSidebar: [
    {
      type: 'category',
      label: 'Data Structures and Algorithms',
      items: ['data-structures-and-algorithms/intro'],
    },
  ],
  leetcodeSidebar: [
    {
      type: 'category',
      label: 'LeetCode Solutions',
      items: ['leetcode/intro'],
    },
  ],
  aboutSidebar: [
    {
      type: 'category',
      label: 'About',
      items: ['about/index'],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
